# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: marvel
  datasource:
    url: jdbc:h2:mem:marveldb
    username: mary
    password: mary
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always	
  main:
    lazy-initialization: false 
marvel:
  api:
    public-key: dc447ee6fb03816e58f8772b02cf8d2f
    private-key: 6908738ed9365147415738f47d69f1669ccf9691
    base-url: https://gateway.marvel.com/v1/public/characters