/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Cable
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.client.model.CharacterList;
import io.swagger.client.model.ComicList;
import io.swagger.client.model.CreatorList;
import io.swagger.client.model.EventSummary;
import io.swagger.client.model.Image;
import io.swagger.client.model.SeriesList;
import io.swagger.client.model.StoryList;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Event
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-02-21T01:26:09.968009500-05:00[America/Lima]")
public class Event {
  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("resourceURI")
  private String resourceURI = null;

  @JsonProperty("urls")
  private java.util.List urls = null;

  @JsonProperty("modified")
  private java.util.Date modified = null;

  @JsonProperty("start")
  private java.util.Date start = null;

  @JsonProperty("end")
  private java.util.Date end = null;

  @JsonProperty("thumbnail")
  private Image thumbnail = null;

  @JsonProperty("comics")
  private ComicList comics = null;

  @JsonProperty("stories")
  private StoryList stories = null;

  @JsonProperty("series")
  private SeriesList series = null;

  @JsonProperty("characters")
  private CharacterList characters = null;

  @JsonProperty("creators")
  private CreatorList creators = null;

  @JsonProperty("next")
  private EventSummary next = null;

  @JsonProperty("previous")
  private EventSummary previous = null;

  public Event id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Event title(String title) {
    this.title = title;
    return this;
  }

   /**
   * The title of the event.
   * @return title
  **/
  @Schema(description = "The title of the event.")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public Event description(String description) {
    this.description = description;
    return this;
  }

   /**
   * A description of the event.
   * @return description
  **/
  @Schema(description = "A description of the event.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Event resourceURI(String resourceURI) {
    this.resourceURI = resourceURI;
    return this;
  }

   /**
   * The canonical URL identifier for this resource.
   * @return resourceURI
  **/
  @Schema(description = "The canonical URL identifier for this resource.")
  public String getResourceURI() {
    return resourceURI;
  }

  public void setResourceURI(String resourceURI) {
    this.resourceURI = resourceURI;
  }

  public Event urls(java.util.List urls) {
    this.urls = urls;
    return this;
  }

   /**
   * Get urls
   * @return urls
  **/
  @Schema(description = "")
  public java.util.List getUrls() {
    return urls;
  }

  public void setUrls(java.util.List urls) {
    this.urls = urls;
  }

  public Event modified(java.util.Date modified) {
    this.modified = modified;
    return this;
  }

   /**
   * Get modified
   * @return modified
  **/
  @Schema(description = "")
  public java.util.Date getModified() {
    return modified;
  }

  public void setModified(java.util.Date modified) {
    this.modified = modified;
  }

  public Event start(java.util.Date start) {
    this.start = start;
    return this;
  }

   /**
   * Get start
   * @return start
  **/
  @Schema(description = "")
  public java.util.Date getStart() {
    return start;
  }

  public void setStart(java.util.Date start) {
    this.start = start;
  }

  public Event end(java.util.Date end) {
    this.end = end;
    return this;
  }

   /**
   * Get end
   * @return end
  **/
  @Schema(description = "")
  public java.util.Date getEnd() {
    return end;
  }

  public void setEnd(java.util.Date end) {
    this.end = end;
  }

  public Event thumbnail(Image thumbnail) {
    this.thumbnail = thumbnail;
    return this;
  }

   /**
   * Get thumbnail
   * @return thumbnail
  **/
  @Schema(description = "")
  public Image getThumbnail() {
    return thumbnail;
  }

  public void setThumbnail(Image thumbnail) {
    this.thumbnail = thumbnail;
  }

  public Event comics(ComicList comics) {
    this.comics = comics;
    return this;
  }

   /**
   * Get comics
   * @return comics
  **/
  @Schema(description = "")
  public ComicList getComics() {
    return comics;
  }

  public void setComics(ComicList comics) {
    this.comics = comics;
  }

  public Event stories(StoryList stories) {
    this.stories = stories;
    return this;
  }

   /**
   * Get stories
   * @return stories
  **/
  @Schema(description = "")
  public StoryList getStories() {
    return stories;
  }

  public void setStories(StoryList stories) {
    this.stories = stories;
  }

  public Event series(SeriesList series) {
    this.series = series;
    return this;
  }

   /**
   * Get series
   * @return series
  **/
  @Schema(description = "")
  public SeriesList getSeries() {
    return series;
  }

  public void setSeries(SeriesList series) {
    this.series = series;
  }

  public Event characters(CharacterList characters) {
    this.characters = characters;
    return this;
  }

   /**
   * Get characters
   * @return characters
  **/
  @Schema(description = "")
  public CharacterList getCharacters() {
    return characters;
  }

  public void setCharacters(CharacterList characters) {
    this.characters = characters;
  }

  public Event creators(CreatorList creators) {
    this.creators = creators;
    return this;
  }

   /**
   * Get creators
   * @return creators
  **/
  @Schema(description = "")
  public CreatorList getCreators() {
    return creators;
  }

  public void setCreators(CreatorList creators) {
    this.creators = creators;
  }

  public Event next(EventSummary next) {
    this.next = next;
    return this;
  }

   /**
   * Get next
   * @return next
  **/
  @Schema(description = "")
  public EventSummary getNext() {
    return next;
  }

  public void setNext(EventSummary next) {
    this.next = next;
  }

  public Event previous(EventSummary previous) {
    this.previous = previous;
    return this;
  }

   /**
   * Get previous
   * @return previous
  **/
  @Schema(description = "")
  public EventSummary getPrevious() {
    return previous;
  }

  public void setPrevious(EventSummary previous) {
    this.previous = previous;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Event event = (Event) o;
    return Objects.equals(this.id, event.id) &&
        Objects.equals(this.title, event.title) &&
        Objects.equals(this.description, event.description) &&
        Objects.equals(this.resourceURI, event.resourceURI) &&
        Objects.equals(this.urls, event.urls) &&
        Objects.equals(this.modified, event.modified) &&
        Objects.equals(this.start, event.start) &&
        Objects.equals(this.end, event.end) &&
        Objects.equals(this.thumbnail, event.thumbnail) &&
        Objects.equals(this.comics, event.comics) &&
        Objects.equals(this.stories, event.stories) &&
        Objects.equals(this.series, event.series) &&
        Objects.equals(this.characters, event.characters) &&
        Objects.equals(this.creators, event.creators) &&
        Objects.equals(this.next, event.next) &&
        Objects.equals(this.previous, event.previous);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, title, description, resourceURI, urls, modified, start, end, thumbnail, comics, stories, series, characters, creators, next, previous);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Event {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    resourceURI: ").append(toIndentedString(resourceURI)).append("\n");
    sb.append("    urls: ").append(toIndentedString(urls)).append("\n");
    sb.append("    modified: ").append(toIndentedString(modified)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("    thumbnail: ").append(toIndentedString(thumbnail)).append("\n");
    sb.append("    comics: ").append(toIndentedString(comics)).append("\n");
    sb.append("    stories: ").append(toIndentedString(stories)).append("\n");
    sb.append("    series: ").append(toIndentedString(series)).append("\n");
    sb.append("    characters: ").append(toIndentedString(characters)).append("\n");
    sb.append("    creators: ").append(toIndentedString(creators)).append("\n");
    sb.append("    next: ").append(toIndentedString(next)).append("\n");
    sb.append("    previous: ").append(toIndentedString(previous)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
